### ISSUE TITLE
Silicon Crash on Windows

### ISSUE THREAD

**Issue by ArquintL** [viperproject/gobra-ide#21]
Silicon crashes when attempting to parse the program ID as a file path on Windows.
This issue is exhibited in [CI run #314](https://github.com/viperproject/gobra-ide/runs/2519398993?check_suite_focus=true).
The corresponding stack trace is:
```
[Gobra IDE - Server] java.nio.file.InvalidPathException: Illegal char <:> at index 12: _programID_d:\a\gobra-ide\gobra-ide\gobra-ide\client\src\test\data\failing_post.go
    at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
    at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
    at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
    at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
    at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
    at java.base/java.nio.file.Path.of(Path.java:147)
    at java.base/java.nio.file.Paths.get(Paths.java:69)
    at viper.silicon.Silicon.$anonfun$verify$1(Silicon.scala:179)
    at viper.silicon.Silicon.$anonfun$verify$1$adapted(Silicon.scala:177)
    at scala.Option.foreach(Option.scala:437)
    at org.rogach.scallop.ScallopOption.foreach(ScallopOption.scala:90)
    at viper.silicon.Silicon.verify(Silicon.scala:177)
    at viper.silicon.Silicon.verify(Silicon.scala:157)
    at viper.server.core.ViperBackend.doCachedVerification(VerificationWorker.scala:186)
    at viper.server.core.ViperBackend.execute(VerificationWorker.scala:136)
    at viper.server.core.VerificationWorker.run(VerificationWorker.scala:65)
    at viper.server.core.VerificationWorker.call(VerificationWorker.scala:104)
    at viper.server.core.VerificationWorker.call(VerificationWorker.scala:32)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

This is an issue in ViperServer and/or Silicon and is already fixed in this ViperServer commit:
https://github.com/viperproject/viperserver/commit/43bc4a8829b0f634d8f371dbf7c609a99859cb21

**Comment by ArquintL** [comment]
The corresponding fixes have been merged in ViperServer and Silicon
